### ISSUE TITLE
link to dowload dataset broken

### ISSUE THREAD

**Issue by moxgreen** [shenlongchen/maresnet#1]
I would like to train model using MAResNet, but the dataset example required to run `train_on_cell_datasets.py` and similar scrip is not abailable since http://csbio.njust.edu.cn/bioinf/maresnet/datasets.html is broken.

**Comment by shenlongchen** [comment]
Sorry. We currently can not provide this service due to the strict web access policy of our university. We will recover this service as soon as possible. The source datasets come from http://cnn.csail.mit.edu/motif_discovery/. you can download from here.
